### ISSUE TITLE
gcloud utility not working

### ISSUE THREAD

**Issue by yaalaa** [GoogleCloudPlatform/python-runtime#25] opened 2016-08-09 09:56 UTC
I failed to run `gcloud` utility (https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-120.0.0-linux-x86_64.tar.gz) with this image.

It seems like valuable requests get no response.
For instance, `gcloud app versions list --log-http --verbosity debug`

 freezes/fails on services API:

```
--request-start--
uri: https://appengine.googleapis.com/v1beta5/apps/<project_id>/services?alt=json
method: GET
-headers-start-
Authorization: Bearer <token>
accept: application/json
accept-encoding: gzip, deflate
content-length: 0
user-agent: blablabla gcloud/120.0.0 command/gcloud.app.versions.list invocation-id/blablabla environment/GCE environment-version/None interactive/True python/2.7.9 (Linux 3.16.0-4-amd64)
-headers-end-
-body-start-
-body-end-
--request-end--
DEBUG: Caught HTTP error ResponseNotReady, retrying: 
DEBUG: Retrying request to url https://appengine.googleapis.com/v1beta5/apps/<project_id>/services?alt=json
 after exception 
--request-start--
```

The following command fails with similar symptoms
`gcloud app services list`

Any idea how to fix it?

**Comment by jonparrott** [comment] 2016-08-09 16:24
I'll take a look. How are you installing gcloud in the container?

**Comment by yaalaa** [comment] 2016-08-09 16:27
```
ADD https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-120.0.0-linux-x86_64.tar.gz /app/
RUN cd /app && tar -xzf google-cloud-sdk-120.0.0-linux-x86_64.tar.gz && rm -f ./google-cloud-sdk-120.0.0-linux-x86_64.tar.gz
ENV CLOUDSDK_PYTHON /env/bin/python
RUN CLOUDSDK_CORE_DISABLE_PROMPTS=1 cd /app/google-cloud-sdk && ./install.sh --usage-reporting false --command-completion false --path-update false --quiet
```

**Comment by jonparrott** [comment] 2016-08-11 21:52
I was about to get `gcloud compute instances list` to work. Can you confirm if that works for you? If so, this may be an issue with the App Engine Admin API.

**Comment by jonparrott** [comment] 2016-08-11 21:53
fwiw, I tried using `gcloud app services list` and `gcloud app versions list` but the request just hangs. So I think we're seeing the same thing.

**Comment by yaalaa** [comment] 2016-08-11 22:10
you're correct, `gcloud compute instances list` works.
`gcloud app versions list` hangs, at least.
what the issue do you suppose with `App Engine Admin API`?

**Comment by jonparrott** [comment] 2016-08-11 22:14
I'm not sure at this point. I've filed a bug internally and will update this when I can.

One thing you can try to do is use a service account key file explicitly with gcloud. You can upload the keyfile with your app and use `gcloud auth activate-service-account`.

**Comment by yaalaa** [comment] 2016-08-11 22:26
I wanna tell you a secret.
Please take a look at https://code.google.com/p/google-cloud-platform/issues/detail?id=86
That's the result of my post ~5 days ago to https://groups.google.com/d/msgid/google-appengine/66dbbf1d-c20c-41e7-8a34-0f65a05fe1d5%40googlegroups.com?utm_medium=email&utm_source=footer

Finally Nick filed a bug, the bug is `Accepted`, I think it means `Confirmed`, not sure.
The steps look similar to what you suggest me to try.

What do you think about it all?

**Comment by jonparrott** [comment] 2016-08-12 16:15
I see - I actually filed a bug with the gcloud sdk team instead of the app engine team. We'll see where they both go.

**Comment by yaalaa** [comment] 2016-08-12 20:45
Could you paste a link to the filed issue?

**Comment by jonparrott** [comment] 2016-08-12 21:10
It's not on a public issue tracker (it's an internal bug).

It seems that the root cause here is that Flex currently redirects all requests to the App Engine Admin API to an internal service. This is to support the compat runtimes. I'm not sure when this will change, but it seems like you won't be able to hit that API from within Flex.

**Comment by duggelz** [comment] 2016-11-30 00:56
I could not reproduce this with the 135.0.0 Cloud SDK and gcr.io/google_appengine/python:2016-11-10_06_11 image.  I'll close this as Fixed.  Please reopen if that is not the case.

**Comment by yaalaa** [comment] 2016-12-22 19:43
At the first glance, all remains the same.
I've used `gcloud` `v137.0.1`.
Not quite sure about base image version, but GCP console says its `debian-7-wheezy-v20161205-rc02`
Issue `gcloud app versions list --quiet --configuration default --format json`
It freezes for about 10 mins then fails with
```
ERROR: (gcloud.app.versions.list)
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
```

**Comment by yaalaa** [comment] 2016-12-22 19:43
@jonparrott, @duggelz please re-open

**Comment by yaalaa** [comment] 2017-01-25 16:57
It seems it's working with new flexible VMs.

**Comment by duggelz** [comment] 2017-01-25 20:30
Great.  I'll close this, but if there are any more problems, please reach out again.

**Closed by duggelz** 2017-01-25 20:30 UTC

**Comment by ipedrazas** [comment] 2018-03-24 10:43
I have the same problem:

```
-> %  gcloud app versions list --quiet --configuration default --format json
ERROR: (gcloud.app.versions.list)
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
```

in case you need the version of the gcloud

```
-> %  gcloud version
Google Cloud SDK 194.0.0
beta 2017.09.15
bq 2.0.30
core 2018.03.16
gcloud
gsutil 4.29
```

Could you please remove this `Please check your network settings` from the error message? clearly, it's not a connectivity issue and the message is misleading

**Comment by duggelz** [comment] 2018-03-27 19:29
@ipedrazas We'll need a little more information.  Can you please paste the contents of your app.yaml, or, if it contains confidential information, please open a ticket with Cloud Support.

**Comment by shettyrahul** [comment] 2019-07-08 14:36
Hi There, 

My projects are not deploying using gcloud. I get the following error too:
"This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach"
So I tried with the HelloWorld code of Google GitHub for AppEngine and tried to deploy:

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/hello-world

But even this does not work. 
Following is what I get from the logs:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@6.10.0
3 info using node@v10.16.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle appengine-hello-world@0.0.1~predeploy: appengine-hello-world@0.0.1
6 info lifecycle appengine-hello-world@0.0.1~deploy: appengine-hello-world@0.0.1
7 verbose lifecycle appengine-hello-world@0.0.1~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle appengine-hello-world@0.0.1~deploy: PATH: C:\Users\Rahul\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Projects\samples\appengine\hello-world\flexible\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;;C:\Program Files (x86)\Google\google_appengine\;C:\Users\Rahul\AppData\Local\Microsoft\WindowsApps;C:\Users\Rahul\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Rahul\AppData\Roaming\npm;C:\Users\Rahul\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin
9 verbose lifecycle appengine-hello-world@0.0.1~deploy: CWD: D:\Projects\samples\appengine\hello-world\flexible
10 silly lifecycle appengine-hello-world@0.0.1~deploy: Args: [ '/d /s /c', 'gcloud app deploy' ]
11 silly lifecycle appengine-hello-world@0.0.1~deploy: Returned: code: 1  signal: null
12 info lifecycle appengine-hello-world@0.0.1~deploy: Failed to exec deploy script
13 verbose stack Error: appengine-hello-world@0.0.1 deploy: `gcloud app deploy`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Rahul\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Rahul\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid appengine-hello-world@0.0.1
15 verbose cwd D:\Projects\samples\appengine\hello-world\flexible
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
18 verbose node v10.16.0
19 verbose npm  v6.10.0
20 error code ELIFECYCLE
21 error errno 1
22 error appengine-hello-world@0.0.1 deploy: `gcloud app deploy`
22 error Exit status 1
23 error Failed at the appengine-hello-world@0.0.1 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by anm237** [comment] 2021-06-18 04:10
I am facing the same issue, can we reopen this issue and have a concrete solution to this problem.

**Comment by anm237** [comment] 2021-06-18 04:58
I found the solution. We need to set up the following:
```gcloud config set proxy/type [PROTOCOL]
gcloud config set proxy/address [PROXY ADDRESS OR IP]
gcloud config set proxy/port [PORT]
set CLOUDSDK_PROXY_USERNAME=[USERNAME]
set CLOUDSDK_PROXY_PASSWORD=[PASSWORD]```
Then, I executed this command
`gcloud config set auth/disable_ssl_validation  True`
Then, when I tried to deploy with `gcloud app deploy`, it worked
